services:
  user-service:
    image: samuelmlee/capitalcompass-users:v0.1
    volumes:
      - C:/Users/sam_m/.aws:/home/cnb/.aws:ro
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  stock-service:
    image: samuelmlee/capitalcompass-stocks:v0.1
    volumes:
      - C:/Users/sam_m/.aws:/home/cnb/.aws:ro
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  gateway:
    image: samuelmlee/capitalcompass-gateway:v0.1
    volumes:
      - C:/Users/sam_m/.aws:/home/cnb/.aws:ro
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker