services:
  user-service:
    image: samuelmlee/capitalcompass-user-service:v0.0.1
    volumes:
      - C:/Users/sam_m/.aws:/home/cnb/.aws:ro
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  stock-service:
    image: samuelmlee/capitalcompass-stock-service:v0.0.1
    volumes:
      - C:/Users/sam_m/.aws:/home/cnb/.aws:ro
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  gateway:
    image: samuelmlee/capitalcompass-gateway:v0.0.1
    volumes:
      - C:/Users/sam_m/.aws:/home/cnb/.aws:ro
    ports:
      - "8443:8443"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  redis:
    image: redis:7.2.3

