services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/capital-compass-deployment/nginx/ec2/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl:/etc/nginx/ssl:ro
    restart: unless-stopped